from typing import Literal

import numpy as np
import pandas as pd
import cv2
import logging


def preprocess_data(
    data: pd.DataFrame,
    confidence_threshold: float = 0.95,
    cropping_mode: Literal["pad", "shift", None] = "shift",
    rescale_to: tuple[int, int] | None = (224, 224),
    **kwargs,
    # TODO: augmentations
) -> pd.DataFrame:
    """
    Preprocess the data.

    Args:
    -----
    data: pd.DataFrame
        The data to preprocess containing the columns:
        - 'image_id': The id of the image. Unique, used to locate image in downstream tasks.
        - 'image': The matrix representation of the image.
        - 'confidence': The confidence score of the bounding box.
        - 'bbox': The relativebounding box coordinates of the animal in the image.
        - 'sex': The sex of the animal if labeled (male, female, unknown).
        - 'age': The age of the animal if labeled (yearling, adult, juvenile, unknown).
        - other metadata columns.
    NOTE: The columns names are generated by the bbox cli tool, subject to change. Provide mapping?

    confidence_threshold: float
        The confidence threshold to use for the bounding box.
        If a bounding box has a confidence score below this threshold, it is excluded from the
        dataset.

    croppping_mode: str
        If "pad", crop the image to a square and pad.
        If "shift", square and try to shift the cropping box to fit within the image bounds.
            Otherwise, pad.
        If None, return the uncropped image.

    rescale_to: tuple[int, int]
        Target size for image resizing. 224 x 224 is recommended.

    Yields:
    -------
    tuple(pd.DataFrame, pd.DataFrame)
        A tuple of dataframes, train and test.
    """
    logging.info(f"Starting preprocessing with {len(data)} images")
    logging.info(
        f"Using confidence threshold: {confidence_threshold}, cropping mode: {cropping_mode}, rescale size: {rescale_to[0]}x{rescale_to[1]}"
    )

    preprocessed_data = data[data["confidence"] >= confidence_threshold].drop(
        columns=["confidence"]
    )
    logging.info(f"Filtered to {len(preprocessed_data)} images after confidence threshold")

    if cropping_mode == "shift":
        logging.info("Applying shift cropping mode")
        preprocessed_data["image"] = preprocessed_data.apply(
            lambda row: crop_image(row["image"], row["bbox"], "shift")
            if row["image"] is not None
            else None,
            axis=1,
        )
    elif cropping_mode == "pad":
        logging.info("Applying pad cropping mode")
        preprocessed_data["image"] = preprocessed_data.apply(
            lambda row: crop_image(row["image"], row["bbox"], "pad")
            if row["image"] is not None
            else None,
            axis=1,
        )
    else:
        raise ValueError(f"Invalid cropping mode: {cropping_mode}. Use 'shift' or 'pad'.")

    if rescale_to is not None:
        logging.info(f"Rescaling images to {rescale_to[0]}x{rescale_to[1]}")
        preprocessed_data["image"] = rescale_images(preprocessed_data["image"], rescale_to)

    logging.info("Transformations completed successfully")
    return preprocessed_data


def crop_image(
    full_image: str,
    bbox_coords: list[int, int, int, int],
    cropping_mode: Literal["shift", "pad", None] = "shift",
) -> np.ndarray:
    """
    Load and crop an image based on the bounding box coordinates. Results in a square image that
    contains the full bounding box, padded with zeros where it exceeds the image bounds.

    Args:
    -----
    image_path: str
        The absolute path to the uncropped image.
    bbox_coords: list[int, int, int, int]
        The bounding box coordinates of the animal in the image.

    Returns:
    --------
    np.ndarray
    """
    logging.debug(f"Cropping image with mode: {cropping_mode}, bbox: {bbox_coords}")
    x_coords, y_coords = get_absolute_coords(bbox_coords, full_image.shape[:2])
    logging.debug(f"Absolute coordinates - x: {x_coords}, y: {y_coords}")

    if cropping_mode == "shift":
        cropped_image = _crop_image(full_image, x_coords, y_coords)
    elif cropping_mode == "pad":
        cropped_image = _crop_and_pad_image(full_image, x_coords, y_coords)
    logging.debug(f"Cropped image shape: {cropped_image.shape}")
    return cropped_image


def get_absolute_coords(
    bbox_coords: list[int, int, int, int], image_shape: tuple[int, int]
) -> tuple[tuple[int, int], tuple[int, int]]:
    """
    Get the absolute coordinates of the bounding box.

    Args:
    -----
    bbox_coords: list[int, int, int, int]
        The bounding box coordinates, proportion of image width/height.
    image_shape: tuple[int, int]
        The shape of the image, (width, height).

    Returns:
    --------
    tuple[tuple[int, int], tuple[int, int]]
        The absolute coordinates of the bounding box. (x_min, x_max), (y_min, y_max)
    """
    # Convert proportional coordinates to absolute pixel values
    # image_shape is (height, width) from OpenCV
    height, width = image_shape
    logging.warning(f"Bbox coords: {bbox_coords}, image shape: {image_shape}")

    # Check if coords are x_min, y_min, width, height OR x_min, y_min, x_max, y_max
    try:
        x_min, y_min, bbox_width, bbox_height = bbox_coords
        assert x_min >= 0 and y_min >= 0 and x_min + bbox_width <= 1 and y_min + bbox_height <= 1
        x_coords = (int(x_min * width), int((x_min + bbox_width) * width))
        y_coords = (int(y_min * height), int((y_min + bbox_height) * height))
        logging.warning("Detected coord format: x_min, y_min, width, height")
    except AssertionError:
        x_min, y_min, x_max, y_max = bbox_coords
        x_coords = (int(x_min * width), int(x_max * width))
        y_coords = (int(y_min * height), int(y_max * height))
        logging.warning("Detected coord format: x_min, y_min, x_max, y_max")

    result = (min(x_coords), max(x_coords)), (min(y_coords), max(y_coords))
    logging.warning(f"Converted coordinates - x: {result[0]}, y: {result[1]}")
    return result


def _crop_and_pad_image(
    image: np.ndarray, x_coords: tuple[int, int], y_coords: tuple[int, int]
) -> np.ndarray:
    """
    Shift the bounding box as much as possible to keep it inside the image, then crop to square with padding.

    Args:
    -----
    image: np.ndarray
        The image to crop and pad.
    x_coords: tuple[int, int]
        The x coordinates of the bounding box.
    y_coords: tuple[int, int]
        The y coordinates of the bounding box.

    Returns:
    --------
    np.ndarray
        The cropped and padded image.
    """
    height, width = image.shape[:2]
    x_min, x_max = x_coords
    y_min, y_max = y_coords
    crop_size = max(x_max - x_min, y_max - y_min)

    logging.debug(f"Padding image: size={crop_size}, original shape={image.shape}")

    if crop_size <= 0:
        raise ValueError(f"Invalid crop size: {crop_size}. Check bounding box coordinates.")

    # Calculate initial crop boundaries centered on bbox
    crop_x_start, crop_x_end, crop_y_start, crop_y_end = _calculate_centered_crop(
        x_coords, y_coords, width, height, crop_size
    )

    # Shift boundaries to keep them within image bounds
    crop_x_start, crop_x_end, crop_y_start, crop_y_end = _shift_crop_boundaries(
        crop_x_start, crop_x_end, crop_y_start, crop_y_end, width, height, crop_size
    )

    # Create a zero-padded array of the desired size
    if len(image.shape) == 3:  # RGB image
        padded = np.zeros((crop_size, crop_size, image.shape[2]), dtype=image.dtype)
    else:  # Grayscale image
        padded = np.zeros((crop_size, crop_size), dtype=image.dtype)

    # Calculate valid crop region (within image bounds)
    x_start = max(0, crop_x_start)
    x_end = min(width, crop_x_end)
    y_start = max(0, crop_y_start)
    y_end = min(height, crop_y_end)

    # Calculate corresponding region in padded array
    pad_x_start = max(0, crop_x_start - x_start)
    pad_y_start = max(0, crop_y_start - y_start)

    # Copy valid portion of image to padded array
    padded[
        pad_y_start : pad_y_start + (y_end - y_start),
        pad_x_start : pad_x_start + (x_end - x_start),
    ] = image[y_start:y_end, x_start:x_end]

    return padded


def _crop_image(
    image: np.ndarray, x_coords: tuple[int, int], y_coords: tuple[int, int]
) -> np.ndarray:
    """
    Try to crop image by shifting bounding box as much as possible to keep the square crop inside the image.
    Only pad if the crop cannot fit even after maximum shifting.

    Args:
    -----
    image: np.ndarray
        The image to crop.
    x_coords: tuple[int, int]
        The x coordinates of the bounding box.
    y_coords: tuple[int, int]
        The y coordinates of the bounding box.

    Returns:
    --------
    np.ndarray
        The cropped image.
    """
    height, width = image.shape[:2]
    x_min, x_max = x_coords
    y_min, y_max = y_coords
    crop_size = max(x_max - x_min, y_max - y_min)

    logging.debug(f"Attempting shift crop: size={crop_size}, original shape={image.shape}")

    if crop_size <= 0:
        raise ValueError(f"Invalid crop size: {crop_size}. Check bounding box coordinates.")

    # Calculate initial crop boundaries centered on bbox
    crop_x_start, crop_x_end, crop_y_start, crop_y_end = _calculate_centered_crop(
        x_coords, y_coords, width, height, crop_size
    )

    # Shift boundaries to keep them within image bounds
    crop_x_start, crop_x_end, crop_y_start, crop_y_end = _shift_crop_boundaries(
        crop_x_start, crop_x_end, crop_y_start, crop_y_end, width, height, crop_size
    )

    # After shifting, check if the crop window is fully inside the image
    if crop_x_start >= 0 and crop_y_start >= 0 and crop_x_end <= width and crop_y_end <= height:
        logging.warning("Maximally shifted crop successful")
        return image[crop_y_start:crop_y_end, crop_x_start:crop_x_end]
    else:
        logging.warning("Maximal shift failed, falling back to padding")
        return _crop_and_pad_image(image, x_coords, y_coords)


def rescale_images(images: list[np.ndarray], rescale_to: tuple[int, int]) -> list[np.ndarray]:
    """
    Rescale images to a 224 x 224 square.
    """
    logging.debug(f"Rescaling {len(images)} images to {rescale_to[0]}x{rescale_to[1]}")
    return [cv2.resize(image, rescale_to) if image is not None else None for image in images]


def _shift_crop_boundaries(
    crop_x_start: int,
    crop_x_end: int,
    crop_y_start: int,
    crop_y_end: int,
    width: int,
    height: int,
    crop_size: int,
) -> tuple[int, int, int, int]:
    """
    Shift crop boundaries to keep them within image bounds.

    Args:
        crop_x_start, crop_x_end, crop_y_start, crop_y_end: Initial crop boundaries
        width, height: Image dimensions
        crop_size: Size of the square crop

    Returns:
        Adjusted crop boundaries (x_start, x_end, y_start, y_end)
    """
    # Handle x-axis violations
    if crop_x_start < 0:
        # Shift right by the violation amount
        shift = abs(crop_x_start)
        crop_x_start += shift
        crop_x_end += shift
    elif crop_x_end > width:
        # Shift left by the violation amount
        shift = crop_x_end - width
        crop_x_start -= shift
        crop_x_end -= shift

    # Handle y-axis violations
    if crop_y_start < 0:
        # Shift down by the violation amount
        shift = abs(crop_y_start)
        crop_y_start += shift
        crop_y_end += shift
    elif crop_y_end > height:
        # Shift up by the violation amount
        shift = crop_y_end - height
        crop_y_start -= shift
        crop_y_end -= shift
    logging.warning(
        f"Shifted crop boundaries: x_start={crop_x_start}, x_end={crop_x_end}, y_start={crop_y_start}, y_end={crop_y_end}"
    )
    return crop_x_start, crop_x_end, crop_y_start, crop_y_end


def _calculate_centered_crop(
    x_coords: tuple[int, int], y_coords: tuple[int, int], width: int, height: int, crop_size: int
) -> tuple[int, int, int, int]:
    """
    Calculate crop boundaries centered on the bounding box.

    Args:
        x_coords, y_coords: Bounding box coordinates
        width, height: Image dimensions
        crop_size: Size of the square crop

    Returns:
        Crop boundaries (x_start, x_end, y_start, y_end)
    """
    x_min, x_max = x_coords
    y_min, y_max = y_coords

    # Calculate center of bounding box
    center_x = (x_min + x_max) // 2
    center_y = (y_min + y_max) // 2
    half_size = crop_size // 2

    # Initial crop boundaries centered on bbox
    crop_x_start = center_x - half_size
    crop_y_start = center_y - half_size
    crop_x_end = crop_x_start + crop_size
    crop_y_end = crop_y_start + crop_size

    return crop_x_start, crop_x_end, crop_y_start, crop_y_end
