import streamlit as st
import logging
import os
import pandas as pd
import json
from PIL import Image, ImageDraw
from pathlib import Path

ANNOTATION_CONFIG = {
    "class_name": st.column_config.TextColumn(
        "Class Name", help="The name of the class to annotate"
    ),
    "class_labels": st.column_config.ListColumn(
        "Class Labels", help="The labels of the class to annotate"
    ),
}


def get_unlabeled_image_dirs():
    """Get all image directories in the data directory that do not have a csv file in them."""
    return [
        d
        for d in os.listdir("data")
        if os.path.isdir(os.path.join("data", d))
        and not os.path.exists(os.path.join("data", d, "annotations.csv"))
    ]


def load_bbox_results(image_dir: str):
    """
    Load Megadetector results for a specific image directory.
    Returns a list of dicts with image file, bbox, and other info.
    """
    # Path to the JSON file generated by Megadetector
    json_path = Path("data") / image_dir / "md_unlabeled.json"
    if not os.path.exists(json_path):
        st.error(f"No bounding box JSON found in {image_dir}")
        return []

    with open(json_path) as f:
        bbox_data = json.load(f)

    # Each key is a unique detection, value is a dict with bbox info
    results = []
    for key, value in bbox_data.items():
        result = {
            "image_path": value.get("file"),
            "bbox": value.get("bbox"),
            "category": value.get("category"),
            "confidence": value.get("confidence"),
            "bbox_id": key,
        }
        results.append(result)

    return results


def render_annotation_page():
    """Render evaluation results for a specific model."""
    st.title("WIP: Annotation")
    image_dir = st.selectbox("Select image directory", get_unlabeled_image_dirs())

    class_df = st.data_editor(
        pd.DataFrame(columns=ANNOTATION_CONFIG.keys(), index=range(1)),
        use_container_width=True,
        num_rows="dynamic",
    )
    if st.button("Continue to annotation"):
        bboxes = load_bbox_results(image_dir)
        if not bboxes:
            st.warning("No bounding boxes found.")
            return

        # Prepare to collect annotations
        annotations = []

        for bbox in bboxes:
            col1, col2 = st.columns(2)
            with col1:
                st.subheader("Image")
                # Load and display image with bounding box
                if os.path.exists(bbox["image_path"]):
                    image = Image.open(bbox["image_path"]).convert("RGB")
                    draw = ImageDraw.Draw(image)
                    # bbox format: [x_start, y_start, x_end, y_end] normalized (0-1)
                    if bbox["bbox"]:
                        w, h = image.size
                        x_start, y_start, x_end, y_end = bbox["bbox"]
                        # Convert normalized coordinates to pixel values
                        box = [x_start * w, y_start * h, x_end * w, y_end * h]
                        draw.rectangle(box, outline="red", width=3)
                    st.image(image, caption=bbox["image_path"], use_column_width=True)
                else:
                    st.error(f"Image not found: {bbox['image_path']}")

            with col2:
                st.subheader("Annotation")
                bbox_annotations = {"bbox_id": bbox["bbox_id"], "image_path": bbox["image_path"]}
                # For each class, show a selectbox for annotation
                for __, row in class_df.iterrows():
                    label = row["class_name"]
                    options = row["class_labels"]
                    selected = st.selectbox(
                        label=label, options=options, key=f"{bbox['bbox_id']}_{label}"
                    )
                    bbox_annotations[label] = selected
                annotations.append(bbox_annotations)

        # Button to save all annotations
        if st.button("Save annotations"):
            # Save to CSV in the image directory
            df = pd.DataFrame(annotations)
            save_path = os.path.join("data", image_dir, "annotations.csv")
            df.to_csv(save_path, index=False)
            st.success(f"Annotations saved to {save_path}")
