# This TOML file specifies the config for running the learning pipeline with test data.
# It contains all the necessary params and can be used as a template for your local IO config.
# Be careful to retain all original variable names and heading structure as outlined here.

# To learn more about TOML syntax, see https://toml.io/en/.

[globals]
# Absolute path or relative path from the wd in which you execute the pipeline
# All other paths are relative to this working directory
working_dir = "." 

#NOTE: input column is "image" by default. 
target_column = "sex"
classes = ["male", "female", "unknown"]

[io]
    ## Data paths (read and write) 
    [io.data] #REQUIRED

    # Parquet file with image, label, and metadata columns
    raw_data_filepath = "data/preprocessed/clean_labeled_bbox_data.parquet"
    # Location for results of `preprocess.py` to use in `train` and `evaluate` steps.
    train_filepath = "data/wildlife_baseline/train.parquet"
    test_filepath = "data/wildlife_baseline/test.parquet"

    ## Model and results paths (read and write)
    [io.model] #REQUIRED

    # Directory to use for trained model (both training specs and model file)
    model_dir = "models/wildlife_baseline"

    # Logging configuration (write)
    [io.logging] #OPTIONAL

    # directory to use for log files. To stream logs to console, comment out or delete this param.
    # One of ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
    log_level = "INFO" 

[preprocess] #OPTIONAL

confidence_threshold = 0.96
cropping_mode = "shift" 
rescale_to = [224, 224]

# Column from your raw data file on which to stratify sampling
# Currently only supports stratification by one column
# To do a train-test split without stratification, delete or comment out this param.
stratify_by = "sex"

[train] #REQUIRED

# DEPRECIATED - NO LONGER USING TENSORFLOW
# Name of a pretrained keras model (or path to pretrained *.keras/*.hd5 model) 
# Or one of ["resnet50v2", "inception_resnet_v2", "vgg19", "xception", "densenet121", "densenet201"]
backbone_model = "/home/chemeryc/wildlife-age-sex/models/lwf_pretrained_model/model.h5" 

batch_size = 32

[evaluate] #OPTIONAL

# Provide stratified evaluation on specified colunm, only supports stratification on one column
stratify_by = "is_summer"
confidence_threshold = 0.85
exclude_uncertain = true